name = "SDLH"
uuid = "29477dde-fb0d-48b9-9d0a-d198f12a030a"
authors = ["Pierre Abbat <phma@bezitopo.org>"]
version = "0.1.0"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
Random = "1.11.0"
